"""
PDF Report Generator for Autonomous Drug Repurposing Discovery Pipeline.
Generates comprehensive clinical R&D summary reports using ReportLab.
"""

from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

class ReportGenerator:
    def __init__(self):
        self.styles = getSampleStyleSheet()

    def generate_repurposing_report(self, disease_name: str, disease_category: str, candidates: list) -> bytes:
        """
        Generates a PDF report summarizing drug repurposing candidate findings.
        """
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
        story = []

        # Title Header
        title_style = ParagraphStyle(
            'ReportTitle',
            parent=self.styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=20,
            leading=24,
            textColor=colors.HexColor('#1e1b4b')
        )
        story.append(Paragraph("Autonomous Drug Repurposing R&D Report", title_style))
        story.append(Spacer(1, 4))

        subtitle_style = ParagraphStyle(
            'ReportSubTitle',
            parent=self.styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=colors.HexColor('#475569')
        )
        story.append(Paragraph(f"Target Indication: <b>{disease_name}</b> ({disease_category}) | GRIET IT Department", subtitle_style))
        story.append(Spacer(1, 10))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#cbd5e1'), spaceBefore=2, spaceAfter=12))

        # Executive Summary
        exec_style = ParagraphStyle(
            'ExecSummary',
            parent=self.styles['Normal'],
            fontName='Helvetica',
            fontSize=9.5,
            leading=13.5,
            textColor=colors.HexColor('#1e293b')
        )
        exec_summary_text = (
            f"This computational candidate shortlist was generated by an Autonomous Closed-Loop Discovery Pipeline. "
            f"Evaluated across 100,000+ chemical compounds using Graph Neural Network (GNN) DTI probability, "
            f"LINCS L1000 gene expression reversal, AutoDock Vina 3D biophysical binding energy (ΔG), and Europe PMC PubMed literature mining."
        )
        story.append(Paragraph(exec_summary_text, exec_style))
        story.append(Spacer(1, 12))

        # Candidates Table Data
        table_data = [
            ["Rank", "Drug Candidate", "Target Gene", "GNN Score", "Docking ΔG", "Est. Ki", "Safety"]
        ]

        for cand in candidates[:10]:
            table_data.append([
                f"#{cand.get('rank', '-')}",
                cand.get('name', 'N/A'),
                cand.get('target_gene', 'N/A'),
                f"{(cand.get('gnn_dti_score', 0) * 100):.1f}%",
                f"{cand.get('docking_delta_g', 0)} kcal/mol",
                f"{cand.get('estimated_ki_nm', 0)} nM",
                f"{(cand.get('safety_score', 0) * 100):.0f}%"
            ])

        t = Table(table_data, colWidths=[35, 150, 75, 65, 80, 65, 55])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f1f5f9')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#0f172a')),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 9),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 6),
            ('TOPPADDING', (0, 0), (-1, 0), 6),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 8.5),
            ('ALIGN', (0, 0), (0, -1), 'CENTER'),
            ('ALIGN', (3, 0), (-1, -1), 'CENTER'),
        ]))
        story.append(t)
        story.append(Spacer(1, 14))

        # Footer Notes
        footer_style = ParagraphStyle(
            'ReportFooter',
            parent=self.styles['Normal'],
            fontName='Helvetica-Oblique',
            fontSize=8,
            leading=11,
            textColor=colors.HexColor('#94a3b8')
        )
        story.append(Paragraph("For investigational R&D reference only. Multi-modal prediction validated against DrugBank 5.0, DisGeNET 7.0, and AutoDock Vina physics engine.", footer_style))

        doc.build(story)
        pdf_bytes = buffer.getvalue()
        buffer.close()
        return pdf_bytes
